version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'saltDB'
    environment:
      - POSTGRES_USER=chilis
      - POSTGRES_PASSWORD=redhot
      - POSTGRES_DB=saltDB
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

