debug: true

server:
  port: ${PORT:8080}
spring:
  sql:
    init:
      platform: postgresql
      mode: always

  output:
    ansi:
      enabled: always

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/saltDB}

    username: ${DB_SALT:chilis}
    password: ${DB_PASSWORD:redhot}


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${OPENAI_API_KEY}